/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instancias;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jugador.Jugador;
import static manejadorDatos.AlmacenamientoUsuarioPlantas.almacenamientoUsuarioPlantas;

/**
 *
 * @author Mariano
 */
public class FrameMercado extends javax.swing.JFrame {

    /**
     * Creates new form FrameMercado
     */
    FondoInicio fondoInicioMercado = new FondoInicio();
    public FrameMercado() {
        this.setContentPane(fondoInicioMercado);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegresarGranjajButton2 = new javax.swing.JButton();
        LogojLabel1 = new javax.swing.JLabel();
        FinalizarJuegojButton2 = new javax.swing.JButton();
        VenderjLabel2 = new javax.swing.JLabel();
        ComprarjButton2 = new javax.swing.JButton();
        FertilizantesjLabel5 = new javax.swing.JLabel();
        VenderjButton3 = new javax.swing.JButton();
        FondojLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercado");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegresarGranjajButton2.setBackground(new java.awt.Color(0, 204, 204));
        RegresarGranjajButton2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        RegresarGranjajButton2.setForeground(new java.awt.Color(0, 0, 0));
        RegresarGranjajButton2.setText("Regresar a Granja");
        RegresarGranjajButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarGranjajButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarGranjajButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 595, -1, -1));

        LogojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Logo.PNG"))); // NOI18N
        jPanel1.add(LogojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 600, -1, -1));

        FinalizarJuegojButton2.setBackground(new java.awt.Color(255, 0, 0));
        FinalizarJuegojButton2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        FinalizarJuegojButton2.setForeground(new java.awt.Color(0, 0, 0));
        FinalizarJuegojButton2.setText("Finalizar juego");
        FinalizarJuegojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarJuegojButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(FinalizarJuegojButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, -1, -1));

        VenderjLabel2.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        VenderjLabel2.setForeground(new java.awt.Color(0, 0, 0));
        VenderjLabel2.setText("Vender");
        jPanel1.add(VenderjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, -1, -1));

        ComprarjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Comprar.PNG"))); // NOI18N
        ComprarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarjButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(ComprarjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 170, 150));

        FertilizantesjLabel5.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        FertilizantesjLabel5.setForeground(new java.awt.Color(0, 0, 0));
        FertilizantesjLabel5.setText("Comprar");
        jPanel1.add(FertilizantesjLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        VenderjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Vender.PNG"))); // NOI18N
        VenderjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderjButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(VenderjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 170, 130));

        FondojLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/FondoMercado.jpg"))); // NOI18N
        jPanel1.add(FondojLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 620, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarGranjajButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarGranjajButton2ActionPerformed
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_RegresarGranjajButton2ActionPerformed

    private void FinalizarJuegojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarJuegojButton2ActionPerformed
        JOptionPane.showMessageDialog(FrameMercado.this, "Fin del juego, vuelve pronto "+Jugador.jugador1.getNick());
        System.exit(0);
    }//GEN-LAST:event_FinalizarJuegojButton2ActionPerformed

    private void ComprarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarjButton2ActionPerformed
        LlamadoInstancias.comprar();
        this.dispose();
    }//GEN-LAST:event_ComprarjButton2ActionPerformed

    private void VenderjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderjButton3ActionPerformed
        if(Jugador.jugador1.getEntradaVentas()>0){       
            LlamadoInstancias.vender();
            this.dispose();
        }                                    
        else{
            JOptionPane.showMessageDialog(null, "Necesitas primero generar alimentos o productos para vender");
        }
        
        
        
    }//GEN-LAST:event_VenderjButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    class FondoInicio extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/decoracion/IrMercado.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComprarjButton2;
    private javax.swing.JLabel FertilizantesjLabel5;
    private javax.swing.JButton FinalizarJuegojButton2;
    private javax.swing.JLabel FondojLabel2;
    private javax.swing.JLabel LogojLabel1;
    private javax.swing.JButton RegresarGranjajButton2;
    private javax.swing.JButton VenderjButton3;
    private javax.swing.JLabel VenderjLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
