/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instancias;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import jugador.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import manejadorDatos.AlmacenamientoUsuarioPlantas;
import static manejadorDatos.AlmacenamientoUsuarioPlantas.almacenamientoUsuarioPlantas;
import static instancias.FrameGranja.*;
import static proyecto1.CrearAnimalesPlantas.*;

/**
 *
 * @author Mariano
 */
public class FrameSeleccionSiembra extends javax.swing.JFrame {

    /**
     * Creates new form FrameSeleccionSiembra
     */
    FondoInicio fondoInicioGranja = new FondoInicio();
    public FrameSeleccionSiembra() {
        this.setContentPane(fondoInicioGranja);
        initComponents();
        AlmacenamientoUsuarioPlantas.visibilidadCompra();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        FinalizarJuegojButton2 = new javax.swing.JButton();
        LogojLabel1 = new javax.swing.JLabel();
        NaranjoSembrarjButton3 = new javax.swing.JButton();
        BananoSembrarjButton4 = new javax.swing.JButton();
        ManzanoSembrarjButton3 = new javax.swing.JButton();
        MaizSembrarjButton2 = new javax.swing.JButton();
        FrijoljSembrarButton2 = new javax.swing.JButton();
        ArrozSembrarjButton1 = new javax.swing.JButton();
        ArrozSembrarjLabel1 = new javax.swing.JLabel();
        MaizSembrarjLabel2 = new javax.swing.JLabel();
        ManzanoSembrarjLabel5 = new javax.swing.JLabel();
        BananoSembrarjLabel6 = new javax.swing.JLabel();
        NaranjoSembrarjLabel3 = new javax.swing.JLabel();
        FrijolSembrarjLabel3 = new javax.swing.JLabel();
        NaranjoSembrarjLabel4 = new javax.swing.JLabel();
        BananoSembrarjLabel7 = new javax.swing.JLabel();
        ManzanoSembrarjLabel6 = new javax.swing.JLabel();
        MaizSembrarjLabel3 = new javax.swing.JLabel();
        FrijolSembrarjLabel4 = new javax.swing.JLabel();
        ArrozSembrarjLabel2 = new javax.swing.JLabel();
        NaranjoSembrarjLabel5 = new javax.swing.JLabel();
        BananoSembrarjLabel8 = new javax.swing.JLabel();
        ManzanoSembrarjLabel7 = new javax.swing.JLabel();
        MaizSembrarjLabel4 = new javax.swing.JLabel();
        FrijolSembrarjLabel5 = new javax.swing.JLabel();
        ArrozSembrarjLabel3 = new javax.swing.JLabel();
        FondojLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar a Granja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        FinalizarJuegojButton2.setBackground(new java.awt.Color(255, 0, 0));
        FinalizarJuegojButton2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        FinalizarJuegojButton2.setForeground(new java.awt.Color(0, 0, 0));
        FinalizarJuegojButton2.setText("Finalizar Juego");
        FinalizarJuegojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarJuegojButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(FinalizarJuegojButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, -1, -1));

        LogojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Logo.PNG"))); // NOI18N
        jPanel1.add(LogojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 600, -1, -1));

        NaranjoSembrarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Naranjo.PNG"))); // NOI18N
        NaranjoSembrarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaranjoSembrarjButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(NaranjoSembrarjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 70, 60));

        BananoSembrarjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Banano.PNG"))); // NOI18N
        BananoSembrarjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BananoSembrarjButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(BananoSembrarjButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 70, 60));

        ManzanoSembrarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Manzano.PNG"))); // NOI18N
        ManzanoSembrarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManzanoSembrarjButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(ManzanoSembrarjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 70, 60));

        MaizSembrarjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Maiz.PNG"))); // NOI18N
        MaizSembrarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaizSembrarjButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(MaizSembrarjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 70, 60));

        FrijoljSembrarButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Frijol.PNG"))); // NOI18N
        FrijoljSembrarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrijoljSembrarButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(FrijoljSembrarButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 50, 60));

        ArrozSembrarjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Arroz.PNG"))); // NOI18N
        ArrozSembrarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrozSembrarjButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(ArrozSembrarjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 70, 60));

        ArrozSembrarjLabel1.setForeground(new java.awt.Color(0, 0, 0));
        ArrozSembrarjLabel1.setText("Arroz");
        jPanel1.add(ArrozSembrarjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));

        MaizSembrarjLabel2.setForeground(new java.awt.Color(0, 0, 0));
        MaizSembrarjLabel2.setText("Maiz");
        jPanel1.add(MaizSembrarjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        ManzanoSembrarjLabel5.setForeground(new java.awt.Color(0, 0, 0));
        ManzanoSembrarjLabel5.setText("Manzano");
        jPanel1.add(ManzanoSembrarjLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        BananoSembrarjLabel6.setForeground(new java.awt.Color(0, 0, 0));
        BananoSembrarjLabel6.setText("Banano");
        jPanel1.add(BananoSembrarjLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        NaranjoSembrarjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        NaranjoSembrarjLabel3.setText("Naranjo");
        jPanel1.add(NaranjoSembrarjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        FrijolSembrarjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        FrijolSembrarjLabel3.setText("Frijol");
        jPanel1.add(FrijolSembrarjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, -1, -1));

        NaranjoSembrarjLabel4.setForeground(new java.awt.Color(0, 0, 0));
        NaranjoSembrarjLabel4.setText("Semillas actuales: "+almacenamientoUsuarioPlantas.getSemillaNaranjo());
        jPanel1.add(NaranjoSembrarjLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        BananoSembrarjLabel7.setForeground(new java.awt.Color(0, 0, 0));
        BananoSembrarjLabel7.setText("Semillas actuales: "+almacenamientoUsuarioPlantas.getSemillaBanano());
        jPanel1.add(BananoSembrarjLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        ManzanoSembrarjLabel6.setForeground(new java.awt.Color(0, 0, 0));
        ManzanoSembrarjLabel6.setText("Semillas actuales: "+almacenamientoUsuarioPlantas.getSemillaManzano());
        jPanel1.add(ManzanoSembrarjLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        MaizSembrarjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        MaizSembrarjLabel3.setText("Semillas actuales: "+almacenamientoUsuarioPlantas.getSemillaMaiz());
        jPanel1.add(MaizSembrarjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        FrijolSembrarjLabel4.setForeground(new java.awt.Color(0, 0, 0));
        FrijolSembrarjLabel4.setText("Semillas actuales: "+almacenamientoUsuarioPlantas.getSemillaFrijol());
        jPanel1.add(FrijolSembrarjLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        ArrozSembrarjLabel2.setForeground(new java.awt.Color(0, 0, 0));
        ArrozSembrarjLabel2.setText("Semillas actuales: "+almacenamientoUsuarioPlantas.getSemillaArroz());
        jPanel1.add(ArrozSembrarjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        NaranjoSembrarjLabel5.setForeground(new java.awt.Color(0, 0, 0));
        NaranjoSembrarjLabel5.setText("Semillas Necesarias: 3");
        jPanel1.add(NaranjoSembrarjLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        BananoSembrarjLabel8.setForeground(new java.awt.Color(0, 0, 0));
        BananoSembrarjLabel8.setText("Semillas Necesarias: 5");
        jPanel1.add(BananoSembrarjLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        ManzanoSembrarjLabel7.setForeground(new java.awt.Color(0, 0, 0));
        ManzanoSembrarjLabel7.setText("Semillas Necesarias: 3");
        jPanel1.add(ManzanoSembrarjLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        MaizSembrarjLabel4.setForeground(new java.awt.Color(0, 0, 0));
        MaizSembrarjLabel4.setText("Semillas Necesarias: 5");
        jPanel1.add(MaizSembrarjLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        FrijolSembrarjLabel5.setForeground(new java.awt.Color(0, 0, 0));
        FrijolSembrarjLabel5.setText("Semillas Necesarias: 8");
        jPanel1.add(FrijolSembrarjLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        ArrozSembrarjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        ArrozSembrarjLabel3.setText("Semillas Necesarias: 8");
        jPanel1.add(ArrozSembrarjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        FondojLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/FondoMercado.jpg"))); // NOI18N
        jPanel1.add(FondojLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 540, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        FrameGranja.visible();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FinalizarJuegojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarJuegojButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Fin del juego, vuelve pronto "+Jugador.jugador1.getNick());
        System.exit(0);
        
    }//GEN-LAST:event_FinalizarJuegojButton2ActionPerformed

    private void NaranjoSembrarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaranjoSembrarjButton3ActionPerformed
        if(almacenamientoUsuarioPlantas.getSemillaNaranjo()>=plantas[4].getSemillasNecesariasSembrar()){
            JOptionPane.showMessageDialog(null, "Seleccionaste naranjo "+Jugador.jugador1.getNick()+" ve a la opcion sembrar y pon tu planta");
            AlmacenamientoUsuarioPlantas.restarNaranjo();
            almacenamientoUsuarioPlantas.setControladorSembrarNaranjo(plantas[4].getSemillasNecesariasSembrar());
            FrameGranja.setVisible(true);           
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No tienes suficientes semillas de naranjo "+Jugador.jugador1.getNick());
        }
    }//GEN-LAST:event_NaranjoSembrarjButton3ActionPerformed

    private void BananoSembrarjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BananoSembrarjButton4ActionPerformed
        if(almacenamientoUsuarioPlantas.getSemillaBanano()>=plantas[5].getSemillasNecesariasSembrar()){
            JOptionPane.showMessageDialog(null, "Seleccionaste banano "+Jugador.jugador1.getNick()+" ve a la opcion sembrar y pon tu planta");
            AlmacenamientoUsuarioPlantas.restarBanano();
            almacenamientoUsuarioPlantas.setControladorSembrarBanano(plantas[5].getSemillasNecesariasSembrar());
            FrameGranja.setVisible(true);           
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No tienes suficientes semillas de banano "+Jugador.jugador1.getNick());
        }
    }//GEN-LAST:event_BananoSembrarjButton4ActionPerformed

    private void ManzanoSembrarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManzanoSembrarjButton3ActionPerformed
        if(almacenamientoUsuarioPlantas.getSemillaManzano()>=plantas[3].getSemillasNecesariasSembrar()){
            JOptionPane.showMessageDialog(null, "Seleccionaste manzano "+Jugador.jugador1.getNick()+" ve a la opcion sembrar y pon tu planta");
            AlmacenamientoUsuarioPlantas.restarManzano();
            almacenamientoUsuarioPlantas.setControladorSembrarManzano(plantas[3].getSemillasNecesariasSembrar());
            FrameGranja.setVisible(true);
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No tienes suficientes semillas de manzano "+Jugador.jugador1.getNick());
        }
    }//GEN-LAST:event_ManzanoSembrarjButton3ActionPerformed

    private void MaizSembrarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaizSembrarjButton2ActionPerformed
        if(almacenamientoUsuarioPlantas.getSemillaMaiz()>=plantas[0].getSemillasNecesariasSembrar()){
            JOptionPane.showMessageDialog(null, "Seleccionaste maiz "+Jugador.jugador1.getNick()+" ve a la opcion sembrar y pon tu planta");
            AlmacenamientoUsuarioPlantas.restarMaiz();
            almacenamientoUsuarioPlantas.setControladorSembrarMaiz(plantas[0].getSemillasNecesariasSembrar());
            FrameGranja.setVisible(true);           
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No tienes suficientes semillas de maiz "+Jugador.jugador1.getNick());
        }
    }//GEN-LAST:event_MaizSembrarjButton2ActionPerformed

    private void FrijoljSembrarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrijoljSembrarButton2ActionPerformed
        if(almacenamientoUsuarioPlantas.getSemillaFrijol()>=plantas[1].getSemillasNecesariasSembrar()){
            JOptionPane.showMessageDialog(null, "Seleccionaste frijol "+Jugador.jugador1.getNick()+" ve a la opcion sembrar y pon tu planta");
            AlmacenamientoUsuarioPlantas.restarFrijol();
            almacenamientoUsuarioPlantas.setControladorSembrarFrijol(plantas[1].getSemillasNecesariasSembrar());
            FrameGranja.setVisible(true);           
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No tienes suficientes semillas de frijol "+Jugador.jugador1.getNick());
        }
    }//GEN-LAST:event_FrijoljSembrarButton2ActionPerformed

    private void ArrozSembrarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrozSembrarjButton1ActionPerformed
        if(almacenamientoUsuarioPlantas.getSemillaArroz()>=plantas[2].getSemillasNecesariasSembrar()){
            JOptionPane.showMessageDialog(null, "Seleccionaste arroz "+Jugador.jugador1.getNick()+" ve a la opcion sembrar y pon tu planta");
            AlmacenamientoUsuarioPlantas.restarArroz();
            almacenamientoUsuarioPlantas.setControladorSembrarArroz(plantas[2].getSemillasNecesariasSembrar());
            FrameGranja.setVisible(true);           
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No tienes suficientes semillas de arroz "+Jugador.jugador1.getNick());
        }
    }//GEN-LAST:event_ArrozSembrarjButton1ActionPerformed
    class FondoInicio extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/decoracion/FondoGranja.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ArrozSembrarjButton1;
    public static javax.swing.JLabel ArrozSembrarjLabel1;
    public static javax.swing.JLabel ArrozSembrarjLabel2;
    public static javax.swing.JLabel ArrozSembrarjLabel3;
    public static javax.swing.JButton BananoSembrarjButton4;
    public static javax.swing.JLabel BananoSembrarjLabel6;
    public static javax.swing.JLabel BananoSembrarjLabel7;
    public static javax.swing.JLabel BananoSembrarjLabel8;
    private javax.swing.JButton FinalizarJuegojButton2;
    private javax.swing.JLabel FondojLabel3;
    public static javax.swing.JLabel FrijolSembrarjLabel3;
    public static javax.swing.JLabel FrijolSembrarjLabel4;
    public static javax.swing.JLabel FrijolSembrarjLabel5;
    public static javax.swing.JButton FrijoljSembrarButton2;
    private javax.swing.JLabel LogojLabel1;
    public static javax.swing.JButton MaizSembrarjButton2;
    public static javax.swing.JLabel MaizSembrarjLabel2;
    public static javax.swing.JLabel MaizSembrarjLabel3;
    public static javax.swing.JLabel MaizSembrarjLabel4;
    public static javax.swing.JButton ManzanoSembrarjButton3;
    public static javax.swing.JLabel ManzanoSembrarjLabel5;
    public static javax.swing.JLabel ManzanoSembrarjLabel6;
    public static javax.swing.JLabel ManzanoSembrarjLabel7;
    public static javax.swing.JButton NaranjoSembrarjButton3;
    public static javax.swing.JLabel NaranjoSembrarjLabel3;
    public static javax.swing.JLabel NaranjoSembrarjLabel4;
    public static javax.swing.JLabel NaranjoSembrarjLabel5;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
