/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instancias;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jugador.*;
import static manejadorDatos.AlmacenamientoUsuarioAlimentos.almacenamientoUsuarioAlimentos;
import static manejadorDatos.AlmacenamientoUsuarioAnimales.almacenamientoUsuarioAnimales;
import manejadorDatos.AlmacenamientoUsuarioPlantas;
import manejadorDatos.EstablecerReportes;
/**
 *
 * @author Mariano
 */
public class FrameComer extends javax.swing.JFrame {

    /**
     * Creates new form FrameComer
     */
    FondoInicio fondoComer = new FondoInicio();
    public FrameComer() {
        this.setContentPane(fondoComer);
        initComponents();
        AlmacenamientoUsuarioPlantas.visibilidadComer();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        FinalizarJuegojButton2 = new javax.swing.JButton();
        LogojLabel1 = new javax.swing.JLabel();
        ZNaranjoSembrarjButton3 = new javax.swing.JButton();
        ZNaranjoSembrarjLabel3 = new javax.swing.JLabel();
        ZManzanoSembrarjButton3 = new javax.swing.JButton();
        ZManzanoSembrarjLabel5 = new javax.swing.JLabel();
        ZBananoSembrarjButton4 = new javax.swing.JButton();
        ZBananoSembrarjLabel6 = new javax.swing.JLabel();
        ZpescarjButton5 = new javax.swing.JButton();
        ZPescadojLabel7 = new javax.swing.JLabel();
        ZNaranjoSembrarjButton4 = new javax.swing.JButton();
        ZNaranjoSembrarjLabel4 = new javax.swing.JLabel();
        ZManzanoSembrarjButton4 = new javax.swing.JButton();
        ZManzanoSembrarjLabel6 = new javax.swing.JLabel();
        ZBananoSembrarjButton5 = new javax.swing.JButton();
        ZBananoSembrarjLabel7 = new javax.swing.JLabel();
        ZFrijoljSembrarButton3 = new javax.swing.JButton();
        ZFrijolSembrarjLabel4 = new javax.swing.JLabel();
        ZMaizSembrarjButton3 = new javax.swing.JButton();
        ZMaizSembrarjLabel3 = new javax.swing.JLabel();
        ZArrozSembrarjButton2 = new javax.swing.JButton();
        ZArrozSembrarjLabel2 = new javax.swing.JLabel();
        FondojLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar a Granja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        FinalizarJuegojButton2.setBackground(new java.awt.Color(255, 0, 0));
        FinalizarJuegojButton2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        FinalizarJuegojButton2.setForeground(new java.awt.Color(0, 0, 0));
        FinalizarJuegojButton2.setText("Finalizar Juego");
        FinalizarJuegojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarJuegojButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(FinalizarJuegojButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, -1, -1));

        LogojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Logo.PNG"))); // NOI18N
        jPanel1.add(LogojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 600, -1, -1));

        ZNaranjoSembrarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Naranjo.PNG"))); // NOI18N
        ZNaranjoSembrarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZNaranjoSembrarjButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(ZNaranjoSembrarjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 70, 60));

        ZNaranjoSembrarjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        ZNaranjoSembrarjLabel3.setText("Frutas Naranjo");
        jPanel1.add(ZNaranjoSembrarjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        ZManzanoSembrarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Manzano.PNG"))); // NOI18N
        ZManzanoSembrarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZManzanoSembrarjButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(ZManzanoSembrarjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 70, 60));

        ZManzanoSembrarjLabel5.setForeground(new java.awt.Color(0, 0, 0));
        ZManzanoSembrarjLabel5.setText("Frutas Manzano");
        jPanel1.add(ZManzanoSembrarjLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        ZBananoSembrarjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Banano.PNG"))); // NOI18N
        ZBananoSembrarjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZBananoSembrarjButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(ZBananoSembrarjButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 70, 60));

        ZBananoSembrarjLabel6.setForeground(new java.awt.Color(0, 0, 0));
        ZBananoSembrarjLabel6.setText("Frutas Banano");
        jPanel1.add(ZBananoSembrarjLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        ZpescarjButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Pescado.PNG"))); // NOI18N
        ZpescarjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZpescarjButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(ZpescarjButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 70, 40));

        ZPescadojLabel7.setForeground(new java.awt.Color(0, 0, 0));
        ZPescadojLabel7.setText("Pescados");
        jPanel1.add(ZPescadojLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, -1, -1));

        ZNaranjoSembrarjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Cerdo.PNG"))); // NOI18N
        ZNaranjoSembrarjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZNaranjoSembrarjButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(ZNaranjoSembrarjButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 70, 60));

        ZNaranjoSembrarjLabel4.setForeground(new java.awt.Color(0, 0, 0));
        ZNaranjoSembrarjLabel4.setText("Carne Cerdo");
        jPanel1.add(ZNaranjoSembrarjLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        ZManzanoSembrarjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Pavo.PNG"))); // NOI18N
        ZManzanoSembrarjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZManzanoSembrarjButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(ZManzanoSembrarjButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 70, 60));

        ZManzanoSembrarjLabel6.setForeground(new java.awt.Color(0, 0, 0));
        ZManzanoSembrarjLabel6.setText("Carne Pavo");
        jPanel1.add(ZManzanoSembrarjLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        ZBananoSembrarjButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Gallina.PNG"))); // NOI18N
        ZBananoSembrarjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZBananoSembrarjButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(ZBananoSembrarjButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 70, 60));

        ZBananoSembrarjLabel7.setForeground(new java.awt.Color(0, 0, 0));
        ZBananoSembrarjLabel7.setText("Carne Gallina");
        jPanel1.add(ZBananoSembrarjLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        ZFrijoljSembrarButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Llama.PNG"))); // NOI18N
        ZFrijoljSembrarButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZFrijoljSembrarButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(ZFrijoljSembrarButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 60, 60));

        ZFrijolSembrarjLabel4.setForeground(new java.awt.Color(0, 0, 0));
        ZFrijolSembrarjLabel4.setText("Carne Llama");
        jPanel1.add(ZFrijolSembrarjLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        ZMaizSembrarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Oveja.PNG"))); // NOI18N
        ZMaizSembrarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZMaizSembrarjButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(ZMaizSembrarjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 70, 60));

        ZMaizSembrarjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        ZMaizSembrarjLabel3.setText("Carne Oveja ");
        jPanel1.add(ZMaizSembrarjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        ZArrozSembrarjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Vaca.PNG"))); // NOI18N
        ZArrozSembrarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZArrozSembrarjButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(ZArrozSembrarjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 70, 60));

        ZArrozSembrarjLabel2.setForeground(new java.awt.Color(0, 0, 0));
        ZArrozSembrarjLabel2.setText("Carne Vaca");
        jPanel1.add(ZArrozSembrarjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        FondojLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/FondoMercado.jpg"))); // NOI18N
        jPanel1.add(FondojLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 540, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        FrameGranja.visible();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FinalizarJuegojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarJuegojButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Fin del juego, vuelve pronto "+Jugador.jugador1.getNick());
        System.exit(0);

    }//GEN-LAST:event_FinalizarJuegojButton2ActionPerformed

    private void ZNaranjoSembrarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZNaranjoSembrarjButton3ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAlimentos.setUsuarioNaranjo(almacenamientoUsuarioAlimentos.getUsuarioNaranjo()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste Naranjo ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_ZNaranjoSembrarjButton3ActionPerformed

    private void ZManzanoSembrarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZManzanoSembrarjButton3ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAlimentos.setUsuarioManzano(almacenamientoUsuarioAlimentos.getUsuarioManzano()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste Manzano ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_ZManzanoSembrarjButton3ActionPerformed

    private void ZBananoSembrarjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZBananoSembrarjButton4ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAlimentos.setUsuarioBanano(almacenamientoUsuarioAlimentos.getUsuarioBanano()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste Banano ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  

    }//GEN-LAST:event_ZBananoSembrarjButton4ActionPerformed

    private void ZpescarjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZpescarjButton5ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAnimales.setUsuarioPeces(almacenamientoUsuarioAnimales.getUsuarioPeces()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste carne de cerdo ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_ZpescarjButton5ActionPerformed

    private void ZNaranjoSembrarjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZNaranjoSembrarjButton4ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAlimentos.setUsuarioCerdo(almacenamientoUsuarioAlimentos.getUsuarioCerdo()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste carne de cerdo ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_ZNaranjoSembrarjButton4ActionPerformed

    private void ZManzanoSembrarjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZManzanoSembrarjButton4ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAlimentos.setUsuarioPavo(almacenamientoUsuarioAlimentos.getUsuarioPavo()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste carne de pavo ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_ZManzanoSembrarjButton4ActionPerformed

    private void ZBananoSembrarjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZBananoSembrarjButton5ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAlimentos.setUsuarioGallina(almacenamientoUsuarioAlimentos.getUsuarioGallina()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste carne de gallina ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_ZBananoSembrarjButton5ActionPerformed

    private void ZFrijoljSembrarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZFrijoljSembrarButton3ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAlimentos.setUsuarioLlama(almacenamientoUsuarioAlimentos.getUsuarioLlama()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste carne de llama ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_ZFrijoljSembrarButton3ActionPerformed

    private void ZMaizSembrarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZMaizSembrarjButton3ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAlimentos.setUsuarioOveja(almacenamientoUsuarioAlimentos.getUsuarioOveja()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste carne de oveja ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_ZMaizSembrarjButton3ActionPerformed

    private void ZArrozSembrarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZArrozSembrarjButton2ActionPerformed
        Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()-1);
        almacenamientoUsuarioAlimentos.setUsuarioVaca(almacenamientoUsuarioAlimentos.getUsuarioVaca()-1);
        Jugador.jugador1.setVida(101);
        JOptionPane.showMessageDialog(null, "Comiste carne de vaca ñam ñam y recuperaste vida");
        EstablecerReportes.sumarComidasConsumidas();
        this.dispose();
        FrameGranja.visible();  
    }//GEN-LAST:event_ZArrozSembrarjButton2ActionPerformed
    class FondoInicio extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/decoracion/ComerSiu.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinalizarJuegojButton2;
    private javax.swing.JLabel FondojLabel3;
    private javax.swing.JLabel LogojLabel1;
    public static javax.swing.JButton ZArrozSembrarjButton2;
    public static javax.swing.JLabel ZArrozSembrarjLabel2;
    public static javax.swing.JButton ZBananoSembrarjButton4;
    public static javax.swing.JButton ZBananoSembrarjButton5;
    public static javax.swing.JLabel ZBananoSembrarjLabel6;
    public static javax.swing.JLabel ZBananoSembrarjLabel7;
    public static javax.swing.JLabel ZFrijolSembrarjLabel4;
    public static javax.swing.JButton ZFrijoljSembrarButton3;
    public static javax.swing.JButton ZMaizSembrarjButton3;
    public static javax.swing.JLabel ZMaizSembrarjLabel3;
    public static javax.swing.JButton ZManzanoSembrarjButton3;
    public static javax.swing.JButton ZManzanoSembrarjButton4;
    public static javax.swing.JLabel ZManzanoSembrarjLabel5;
    public static javax.swing.JLabel ZManzanoSembrarjLabel6;
    public static javax.swing.JButton ZNaranjoSembrarjButton3;
    public static javax.swing.JButton ZNaranjoSembrarjButton4;
    public static javax.swing.JLabel ZNaranjoSembrarjLabel3;
    public static javax.swing.JLabel ZNaranjoSembrarjLabel4;
    public static javax.swing.JLabel ZPescadojLabel7;
    public static javax.swing.JButton ZpescarjButton5;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
