/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instancias;

import proyecto1.Tiempo;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jugador.Jugador;
import static manejadorDatos.AlmacenamientoUsuarioAlimentos.almacenamientoUsuarioAlimentos;
import static manejadorDatos.AlmacenamientoUsuarioAnimales.almacenamientoUsuarioAnimales;
import static manejadorDatos.AlmacenamientoUsuarioComidas.almacenamientoUsuarioComidas;
import manejadorDatos.AlmacenamientoUsuarioPlantas;
import static manejadorDatos.AlmacenamientoUsuarioPlantas.almacenamientoUsuarioPlantas;
import static manejadorDatos.AlmacenamientoUsuarioProductos.almacenamientoUsuarioProductos;
import static manejadorDatos.EstablecerInstruccionesHilos.establecerInstruccionesHilos;
import manejadorDatos.EstablecerReportes;
import static manejadorDatos.EstablecerReportes.establecerReportes;
import static proyecto1.CrearAnimalesPlantas.animales;
import static proyecto1.CrearAnimalesPlantas.plantas;
import proyecto1.LlamarTiempo;

/**
 *
 * @author Mariano
 */
public class FrameGranja extends javax.swing.JFrame{

    /**
     * Creates new form FrameGranja
     */
    
    public Vida vida = new Vida();
    public Tiempo tiempo = new Tiempo();
    FondoInicio fondoInicioGranja = new FondoInicio();

    public static FrameGranja FrameGranja;
    public static void iniciarGranja(){
        FrameGranja=new FrameGranja();
    }
    public static void visible(){
        FrameGranja.setVisible(true);
    }

    public FrameGranja(){
        this.setContentPane(fondoInicioGranja);
        initComponents();
        InicializarSuelos.llamarInicializarSuelos();
        InicializarSuelos.inicializarSuelos.inicializarSuelos();
        InicializarSuelos.inicializarSuelos.inicializarAcciones();
        LlamarTiempo.tiempo();
        tiempo.start();
        vida.start();
        barraVida();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GranjajPanel1 = new javax.swing.JPanel();
        BodegajButton2 = new javax.swing.JButton();
        MercadojButton3 = new javax.swing.JButton();
        ReportesjButton4 = new javax.swing.JButton();
        ProcesarjLabel1 = new javax.swing.JLabel();
        ParcelaSinDestacejToggleButton1 = new javax.swing.JToggleButton();
        LimpiezajLabel2 = new javax.swing.JLabel();
        AccionesjLabel3 = new javax.swing.JLabel();
        PescarjToggleButton4 = new javax.swing.JToggleButton();
        ReportesjLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BodegajLabel2 = new javax.swing.JLabel();
        PescarjLabel3 = new javax.swing.JLabel();
        CrearParcelajLabel4 = new javax.swing.JLabel();
        LimpiarUnaParcelajLabel2 = new javax.swing.JLabel();
        ParcelasjToggleButton5 = new javax.swing.JToggleButton();
        ComerjButton2 = new javax.swing.JButton();
        ComerjLabel3 = new javax.swing.JLabel();
        DarComerAnimalesjLabel2 = new javax.swing.JLabel();
        NoDestacejLabel2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LlamadoNickjLabel1 = new javax.swing.JLabel();
        OrojLabel2 = new javax.swing.JLabel();
        OrojLabel6 = new javax.swing.JLabel();
        LogojLabel7 = new javax.swing.JLabel();
        VidajLabel3 = new javax.swing.JLabel();
        VidajLabel8 = new javax.swing.JLabel();
        VidajProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        LimpiarTerrenoCasillajToggleButton3 = new javax.swing.JToggleButton();
        ComprarTerrenojButton2 = new javax.swing.JButton();
        ComprarTerrenojLabel5 = new javax.swing.JLabel();
        CosecharjLabel3 = new javax.swing.JLabel();
        SiembrarjToggleButton3 = new javax.swing.JToggleButton();
        SembrarjLabel2 = new javax.swing.JLabel();
        SeleccionarAnimalesjButton2 = new javax.swing.JButton();
        MenujLabel4 = new javax.swing.JLabel();
        ColocarAnimalesjToggleButton1 = new javax.swing.JToggleButton();
        SeleccionarPlantajButton2 = new javax.swing.JButton();
        PonerAnimaljLabel7 = new javax.swing.JLabel();
        SeleccionarAnimaljLabel8 = new javax.swing.JLabel();
        SeleccionarPlantajLabel7 = new javax.swing.JLabel();
        CosecharjButton2 = new javax.swing.JButton();
        AlimentarjButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Granja");
        setResizable(false);

        GranjajPanel1.setOpaque(false);
        GranjajPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BodegajButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Bodega.PNG"))); // NOI18N
        BodegajButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodegajButton2ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(BodegajButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 90, 40));

        MercadojButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Mercado.PNG"))); // NOI18N
        MercadojButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercadojButton3ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(MercadojButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 60, 40));

        ReportesjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Reporte.PNG"))); // NOI18N
        ReportesjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesjButton4ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(ReportesjButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 40, 40));

        ProcesarjLabel1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        ProcesarjLabel1.setForeground(new java.awt.Color(0, 0, 0));
        ProcesarjLabel1.setText("Procesar animales");
        GranjajPanel1.add(ProcesarjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        ParcelaSinDestacejToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/SinDestace.PNG"))); // NOI18N
        ParcelaSinDestacejToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcelaSinDestacejToggleButton1ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(ParcelaSinDestacejToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 50, 50));

        LimpiezajLabel2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        LimpiezajLabel2.setForeground(new java.awt.Color(0, 0, 0));
        LimpiezajLabel2.setText("Limpiar y crear parcelas");
        GranjajPanel1.add(LimpiezajLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        AccionesjLabel3.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        AccionesjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        AccionesjLabel3.setText("Acciones");
        GranjajPanel1.add(AccionesjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        PescarjToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Pesca.PNG"))); // NOI18N
        PescarjToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PescarjToggleButton4ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(PescarjToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 60, 50));

        ReportesjLabel1.setForeground(new java.awt.Color(0, 0, 0));
        ReportesjLabel1.setText("Reportes");
        GranjajPanel1.add(ReportesjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mercado");
        GranjajPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        BodegajLabel2.setForeground(new java.awt.Color(0, 0, 0));
        BodegajLabel2.setText("Bodega");
        GranjajPanel1.add(BodegajLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        PescarjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        PescarjLabel3.setText("Pescar");
        GranjajPanel1.add(PescarjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        CrearParcelajLabel4.setForeground(new java.awt.Color(0, 0, 0));
        CrearParcelajLabel4.setText("Crear Parcelas");
        GranjajPanel1.add(CrearParcelajLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        LimpiarUnaParcelajLabel2.setBackground(new java.awt.Color(0, 0, 0));
        LimpiarUnaParcelajLabel2.setForeground(new java.awt.Color(0, 0, 0));
        LimpiarUnaParcelajLabel2.setText("Limpiar un cuadro");
        GranjajPanel1.add(LimpiarUnaParcelajLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        ParcelasjToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Parcela.PNG"))); // NOI18N
        ParcelasjToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcelasjToggleButton5ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(ParcelasjToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 60, 50));

        ComerjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Comer.PNG"))); // NOI18N
        ComerjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComerjButton2ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(ComerjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 60, 50));

        ComerjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        ComerjLabel3.setText("Comer");
        GranjajPanel1.add(ComerjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        DarComerAnimalesjLabel2.setForeground(new java.awt.Color(0, 0, 0));
        DarComerAnimalesjLabel2.setText("Alimentar animales");
        GranjajPanel1.add(DarComerAnimalesjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        NoDestacejLabel2.setForeground(new java.awt.Color(0, 0, 0));
        NoDestacejLabel2.setText("Parcela sin destace");
        GranjajPanel1.add(NoDestacejLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Parcela con destace");
        GranjajPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        GranjajPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 880, 460));

        LlamadoNickjLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        LlamadoNickjLabel1.setForeground(new java.awt.Color(0, 0, 0));
        LlamadoNickjLabel1.setText("Bienvenid@ "+Jugador.jugador1.getNick());
        GranjajPanel1.add(LlamadoNickjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        OrojLabel2.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        OrojLabel2.setForeground(new java.awt.Color(0, 0, 0));
        OrojLabel2.setText(""+Jugador.jugador1.getMonedas());
        GranjajPanel1.add(OrojLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        OrojLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Oro.PNG"))); // NOI18N
        GranjajPanel1.add(OrojLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 50, 40));

        LogojLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Logo.PNG"))); // NOI18N
        GranjajPanel1.add(LogojLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 600, 50, 40));

        VidajLabel3.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        VidajLabel3.setForeground(new java.awt.Color(0, 0, 0));
        VidajLabel3.setText(""+Jugador.jugador1.getVida());
        GranjajPanel1.add(VidajLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        VidajLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Vida.PNG"))); // NOI18N
        GranjajPanel1.add(VidajLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 40, 40));

        VidajProgressBar1.setForeground(new java.awt.Color(255, 0, 0));
        GranjajPanel1.add(VidajProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, 10));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Finalizar juego");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 590, -1, -1));

        LimpiarTerrenoCasillajToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/LimpiarUnaParcela.PNG"))); // NOI18N
        LimpiarTerrenoCasillajToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarTerrenoCasillajToggleButton3ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(LimpiarTerrenoCasillajToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 50, 50));

        ComprarTerrenojButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/ComprarTerreno.PNG"))); // NOI18N
        ComprarTerrenojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarTerrenojButton2ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(ComprarTerrenojButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 60, 50));

        ComprarTerrenojLabel5.setForeground(new java.awt.Color(0, 0, 0));
        ComprarTerrenojLabel5.setText("Comprar terreno");
        GranjajPanel1.add(ComprarTerrenojLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, -1));

        CosecharjLabel3.setForeground(new java.awt.Color(0, 0, 0));
        CosecharjLabel3.setText("Cosechar");
        GranjajPanel1.add(CosecharjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        SiembrarjToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Siembra.PNG"))); // NOI18N
        SiembrarjToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiembrarjToggleButton3ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(SiembrarjToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 70, 50));

        SembrarjLabel2.setForeground(new java.awt.Color(0, 0, 0));
        SembrarjLabel2.setText("Sembrar");
        GranjajPanel1.add(SembrarjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 50, -1));

        SeleccionarAnimalesjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/SeleccionarAnimal.PNG"))); // NOI18N
        SeleccionarAnimalesjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarAnimalesjButton2ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(SeleccionarAnimalesjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 50, 60));

        MenujLabel4.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        MenujLabel4.setForeground(new java.awt.Color(0, 0, 0));
        MenujLabel4.setText("Menu");
        GranjajPanel1.add(MenujLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 25));

        ColocarAnimalesjToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/ColocarAnimal.PNG"))); // NOI18N
        ColocarAnimalesjToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColocarAnimalesjToggleButton1ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(ColocarAnimalesjToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 80, 50));

        SeleccionarPlantajButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/SeleccionarPlantas.PNG"))); // NOI18N
        SeleccionarPlantajButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarPlantajButton2ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(SeleccionarPlantajButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 80, 50));

        PonerAnimaljLabel7.setForeground(new java.awt.Color(0, 0, 0));
        PonerAnimaljLabel7.setText("Poner animal");
        GranjajPanel1.add(PonerAnimaljLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, -1));

        SeleccionarAnimaljLabel8.setForeground(new java.awt.Color(0, 0, 0));
        SeleccionarAnimaljLabel8.setText("Seleccionar Animal");
        GranjajPanel1.add(SeleccionarAnimaljLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        SeleccionarPlantajLabel7.setForeground(new java.awt.Color(0, 0, 0));
        SeleccionarPlantajLabel7.setText("Seleccionar Planta");
        GranjajPanel1.add(SeleccionarPlantajLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        CosecharjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Cosechar.PNG"))); // NOI18N
        CosecharjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosecharjButton2ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(CosecharjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 50, 50));

        AlimentarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/ComerAnimales.PNG"))); // NOI18N
        AlimentarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlimentarjButton3ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(AlimentarjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 60, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Destace.PNG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        GranjajPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 50, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/FondoMenu.jpg"))); // NOI18N
        jLabel6.setText("jLabel4");
        GranjajPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GranjajPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GranjajPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class FondoInicio extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/decoracion/FondoGranja.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    public void barraVida(){
        VidajProgressBar1.setValue(Jugador.jugador1.getVida());
    }
            
    private void SiembrarjToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiembrarjToggleButton3ActionPerformed
        if(SiembrarjToggleButton3.isSelected()==true){
            SiembrarjToggleButton3.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/Sembrando.PNG")));
        }
        else{
            SiembrarjToggleButton3.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/Siembra.PNG")));
        } 
    }//GEN-LAST:event_SiembrarjToggleButton3ActionPerformed
    private void ReportesjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesjButton4ActionPerformed
        this.setVisible(false);
        LlamadoInstancias.reportes();
    }//GEN-LAST:event_ReportesjButton4ActionPerformed

    private void ParcelaSinDestacejToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcelaSinDestacejToggleButton1ActionPerformed
        if(ParcelaSinDestacejToggleButton1.isSelected()){
            ParcelaSinDestacejToggleButton1.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/Procesar.PNG")));
        }
        else{
            ParcelaSinDestacejToggleButton1.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/SinDestace.PNG")));
        }
    }//GEN-LAST:event_ParcelaSinDestacejToggleButton1ActionPerformed

    private void PescarjToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PescarjToggleButton4ActionPerformed
        if(PescarjToggleButton4.isSelected()==true){
            PescarjToggleButton4.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/Pescando.PNG")));
        }
        else{
            PescarjToggleButton4.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/Pesca.PNG")));
        } 
    }//GEN-LAST:event_PescarjToggleButton4ActionPerformed

    private void MercadojButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercadojButton3ActionPerformed
        this.setVisible(false);
        LlamadoInstancias.mercado();
    }//GEN-LAST:event_MercadojButton3ActionPerformed

    private void ParcelasjToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcelasjToggleButton5ActionPerformed
        if(ParcelasjToggleButton5.isSelected()){
            ParcelasjToggleButton5.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/Parcelando.PNG")));
        }
        else{
            ParcelasjToggleButton5.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/Parcela.PNG")));
        }
    }//GEN-LAST:event_ParcelasjToggleButton5ActionPerformed

    private void ComerjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComerjButton2ActionPerformed
        if(Jugador.jugador1.getEntradaVentas()>0){
            LlamadoInstancias.comerSiu();
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(FrameGranja.this, "Primero necesitas conseguir comida en la granja "+Jugador.jugador1.getNick());
        }  
    }//GEN-LAST:event_ComerjButton2ActionPerformed

    private void BodegajButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodegajButton2ActionPerformed
        this.setVisible(false);
        LlamadoInstancias.bodega();    
    }//GEN-LAST:event_BodegajButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(FrameGranja.this, "Fin del juego, vuelve pronto "+Jugador.jugador1.getNick());
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LimpiarTerrenoCasillajToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarTerrenoCasillajToggleButton3ActionPerformed
        if(LimpiarTerrenoCasillajToggleButton3.isSelected()==true){
            LimpiarTerrenoCasillajToggleButton3.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/LimpiarSuelo.PNG")));
        }
        else{
            LimpiarTerrenoCasillajToggleButton3.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/LimpiarUnaParcela.PNG")));
        } 
    }//GEN-LAST:event_LimpiarTerrenoCasillajToggleButton3ActionPerformed

    private void ComprarTerrenojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarTerrenojButton2ActionPerformed
        if(Jugador.jugador1.getMonedas()>=200){
            Jugador.jugador1.setSuelo(Jugador.jugador1.getSuelo()+1);
            InicializarSuelos.inicializarSuelos.generadorCompraTerreno();
            Jugador.jugador1.setMonedas(Jugador.jugador1.getMonedas()-200);
            OrojLabel2.setText(""+Jugador.jugador1.getMonedas());
            EstablecerReportes.establecerReportes.setCeldasCompradas(EstablecerReportes.establecerReportes.getCeldasCompradas()+1);
        }
        else JOptionPane.showMessageDialog(FrameGranja.this, "No tienes suficiente dinero para comprar terreno "+Jugador.jugador1.getNick());
    }//GEN-LAST:event_ComprarTerrenojButton2ActionPerformed

    private void ColocarAnimalesjToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColocarAnimalesjToggleButton1ActionPerformed
        if(ColocarAnimalesjToggleButton1.isSelected()==true){
            ColocarAnimalesjToggleButton1.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/CambiarImagenPonerAnimal.PNG")));
        }
        else{
            ColocarAnimalesjToggleButton1.setIcon(new javax.swing.ImageIcon(FrameGranja.this.getClass().getResource("/decoracion/ColocarAnimal.PNG")));
        } 
    }//GEN-LAST:event_ColocarAnimalesjToggleButton1ActionPerformed

    private void SeleccionarPlantajButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarPlantajButton2ActionPerformed
        if(almacenamientoUsuarioPlantas.getTotalSemillas()>0){
            FrameGranja.setVisible(false);   
            LlamadoInstancias.sembrarSeleccion();                                   
        }                                    
        else{
            JOptionPane.showMessageDialog(null, "Necesitas primero comprar semillas");
        }
    }//GEN-LAST:event_SeleccionarPlantajButton2ActionPerformed

    private void SeleccionarAnimalesjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarAnimalesjButton2ActionPerformed
        if(almacenamientoUsuarioAnimales.getTotalCrias()>0){
            FrameGranja.setVisible(false);   
            LlamadoInstancias.criaSeleccion();                                  
        }                                    
        else{
            JOptionPane.showMessageDialog(null, "Necesitas primero comprar una cria");
        }
    }//GEN-LAST:event_SeleccionarAnimalesjButton2ActionPerformed

    private void AlimentarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlimentarjButton3ActionPerformed
        if(almacenamientoUsuarioComidas.getTotalComidaAnimal()>0){
            if(almacenamientoUsuarioComidas.getBambu()>0){
                almacenamientoUsuarioComidas.setBambu(almacenamientoUsuarioComidas.getBambu()-1);
                JOptionPane.showMessageDialog(null,"Diste de comer Bambu ese o esa muchach@ me llena de orgullo.jpg");
                almacenamientoUsuarioComidas.setTotalComidaAnimal(almacenamientoUsuarioComidas.getTotalComidaAnimal()-1);
            } 
            if(almacenamientoUsuarioComidas.getCarnes()>0){
                almacenamientoUsuarioComidas.setCarnes(almacenamientoUsuarioComidas.getCarnes()-1);
                JOptionPane.showMessageDialog(null,"Diste de comer Carnes ese o esa muchach@ me llena de orgullo.jpg");
                almacenamientoUsuarioComidas.setTotalComidaAnimal(almacenamientoUsuarioComidas.getTotalComidaAnimal()-1);
            }
            if(almacenamientoUsuarioComidas.getConcentrado()>0){
                almacenamientoUsuarioComidas.setConcentrado(almacenamientoUsuarioComidas.getConcentrado()-1);
                JOptionPane.showMessageDialog(null,"Diste de comer Concentrado ese o esa muchach@ me llena de orgullo.jpg");
                almacenamientoUsuarioComidas.setTotalComidaAnimal(almacenamientoUsuarioComidas.getTotalComidaAnimal()-1);
            }
            if(almacenamientoUsuarioComidas.getHierba()>0){
                almacenamientoUsuarioComidas.setHierba(almacenamientoUsuarioComidas.getHierba()-1);
                JOptionPane.showMessageDialog(null,"Diste de comer Hierba ese o esa muchach@ me llena de orgullo.jpg");
                almacenamientoUsuarioComidas.setTotalComidaAnimal(almacenamientoUsuarioComidas.getTotalComidaAnimal()-1);
            }
            if(almacenamientoUsuarioComidas.getHojas()>0){
                almacenamientoUsuarioComidas.setHojas(almacenamientoUsuarioComidas.getHojas()-1);
                JOptionPane.showMessageDialog(null,"Diste de comer Hojas ese o esa muchach@ me llena de orgullo.jpg");
                almacenamientoUsuarioComidas.setTotalComidaAnimal(almacenamientoUsuarioComidas.getTotalComidaAnimal()-1);
            }
            if(almacenamientoUsuarioComidas.getHongos()>0){
                almacenamientoUsuarioComidas.setHongos(almacenamientoUsuarioComidas.getHongos()-1);
                JOptionPane.showMessageDialog(null,"Diste de comer Hongos ese o esa muchach@ me llena de orgullo.jpg");
                almacenamientoUsuarioComidas.setTotalComidaAnimal(almacenamientoUsuarioComidas.getTotalComidaAnimal()-1);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"No has comprado comida para animales");
        }
    }//GEN-LAST:event_AlimentarjButton3ActionPerformed

    private void CosecharjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosecharjButton2ActionPerformed
        if(establecerInstruccionesHilos.getHiloMaiz()==2){
            JOptionPane.showMessageDialog(null,"Lograste cosechar a tiempo, conseguiste "+plantas[0].getProductoCosecha()+" lb de maiz");
            establecerInstruccionesHilos.setHiloMaiz(1);
            almacenamientoUsuarioProductos.setUsuarioMaiz(almacenamientoUsuarioProductos.getUsuarioMaiz()+plantas[0].getProductoCosecha());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+plantas[0].getProductoCosecha());
        }
        if(establecerInstruccionesHilos.getHiloFrijol()==2){
            JOptionPane.showMessageDialog(null,"Lograste cosechar a tiempo, conseguiste "+plantas[1].getProductoCosecha()+" lb de frijol");
            establecerInstruccionesHilos.setHiloFrijol(1);
            almacenamientoUsuarioProductos.setUsuarioFrijol(almacenamientoUsuarioProductos.getUsuarioFrijol()+plantas[1].getProductoCosecha());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+plantas[1].getProductoCosecha());
        }
        if(establecerInstruccionesHilos.getHiloArroz()==2){
            JOptionPane.showMessageDialog(null,"Lograste cosechar a tiempo, conseguiste "+plantas[2].getProductoCosecha()+" lb de arroz");
            establecerInstruccionesHilos.setHiloArroz(1);
            almacenamientoUsuarioProductos.setUsuarioArroz(almacenamientoUsuarioProductos.getUsuarioArroz()+plantas[2].getProductoCosecha());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+plantas[2].getProductoCosecha());
        }
        if(establecerInstruccionesHilos.getHiloManzano()==2){
            JOptionPane.showMessageDialog(null,"Lograste cosechar Manzano a tiempo, conseguiste "+plantas[3].getProductoCosecha()+" frutas de mazano");
            establecerInstruccionesHilos.setHiloManzano(1);
            almacenamientoUsuarioAlimentos.setUsuarioManzano(almacenamientoUsuarioAlimentos.getUsuarioManzano()+plantas[3].getProductoCosecha());
            establecerReportes.setAlimentoGenerado(establecerReportes.getAlimentoGenerado()+plantas[3].getProductoCosecha());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+plantas[3].getProductoCosecha());
        }
        if(establecerInstruccionesHilos.getHiloNaranjo()==2){
            JOptionPane.showMessageDialog(null,"Lograste cosechar a tiempo, conseguiste "+plantas[4].getProductoCosecha()+" frutas de naranjo");
            establecerInstruccionesHilos.setHiloNaranjo(1);
            almacenamientoUsuarioAlimentos.setUsuarioNaranjo(almacenamientoUsuarioAlimentos.getUsuarioNaranjo()+plantas[4].getProductoCosecha());
            establecerReportes.setAlimentoGenerado(establecerReportes.getAlimentoGenerado()+plantas[4].getProductoCosecha());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+plantas[4].getProductoCosecha());
        }
        if(establecerInstruccionesHilos.getHiloBanano()==2){
            JOptionPane.showMessageDialog(null,"Lograste cosechar a tiempo, conseguiste "+plantas[5].getProductoCosecha()+" frutas de banano");
            establecerInstruccionesHilos.setHiloBanano(1);
            almacenamientoUsuarioAlimentos.setUsuarioBanano(almacenamientoUsuarioAlimentos.getUsuarioBanano()+plantas[5].getProductoCosecha());
            establecerReportes.setAlimentoGenerado(establecerReportes.getAlimentoGenerado()+plantas[5].getProductoCosecha());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+plantas[5].getProductoCosecha());
        }
        else{
            JOptionPane.showMessageDialog(null,"Primero necesitas tener lista una cosecha :P ");
        }
    }//GEN-LAST:event_CosecharjButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(establecerInstruccionesHilos.getHiloCerdo()==2){
            JOptionPane.showMessageDialog(null,"Lograste destazar a tiempo, conseguiste "+animales[1].getLibrasCarneGenerada()+" lb de carne de cerdo");
            establecerInstruccionesHilos.setHiloCerdo(1);
            almacenamientoUsuarioAlimentos.setUsuarioCerdo(almacenamientoUsuarioAlimentos.getUsuarioCerdo()+animales[1].getLibrasCarneGenerada());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+animales[1].getLibrasCarneGenerada());
            EstablecerReportes.sumarUnidadesDestazadas();
        }
        if(establecerInstruccionesHilos.getHiloGallina()==2){
            JOptionPane.showMessageDialog(null,"Lograste destazar a tiempo, conseguiste "+animales[0].getLibrasCarneGenerada()+" lb de carne de Gallina");
            establecerInstruccionesHilos.setHiloGallina(1);
            almacenamientoUsuarioAlimentos.setUsuarioGallina(almacenamientoUsuarioAlimentos.getUsuarioGallina()+animales[0].getLibrasCarneGenerada());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+animales[0].getLibrasCarneGenerada());
            EstablecerReportes.sumarUnidadesDestazadas();
        }
        if(establecerInstruccionesHilos.getHiloPavo()==2){
            JOptionPane.showMessageDialog(null,"Lograste destazar a tiempo, conseguiste "+animales[2].getLibrasCarneGenerada()+" lb de carne de Pavo");
            establecerInstruccionesHilos.setHiloPavo(1);
            almacenamientoUsuarioAlimentos.setUsuarioPavo(almacenamientoUsuarioAlimentos.getUsuarioPavo()+animales[2].getLibrasCarneGenerada());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+animales[2].getLibrasCarneGenerada());
            EstablecerReportes.sumarUnidadesDestazadas();
        }
        if(establecerInstruccionesHilos.getHiloVaca()==2){
            JOptionPane.showMessageDialog(null,"Lograste destazar a tiempo, conseguiste "+animales[3].getLibrasCarneGenerada()+" lb de carne de Vaca");
            establecerInstruccionesHilos.setHiloVaca(1);
            almacenamientoUsuarioAlimentos.setUsuarioVaca(almacenamientoUsuarioAlimentos.getUsuarioVaca()+animales[3].getLibrasCarneGenerada());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+animales[3].getLibrasCarneGenerada());
            EstablecerReportes.sumarUnidadesDestazadas();
        }
        if(establecerInstruccionesHilos.getHiloOveja()==2){
            JOptionPane.showMessageDialog(null,"Lograste destazar a tiempo, conseguiste "+animales[4].getLibrasCarneGenerada()+" lb de carne de Oveja");
            establecerInstruccionesHilos.setHiloOveja(1);
            almacenamientoUsuarioAlimentos.setUsuarioOveja(almacenamientoUsuarioAlimentos.getUsuarioOveja()+animales[4].getLibrasCarneGenerada());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+animales[4].getLibrasCarneGenerada());
            EstablecerReportes.sumarUnidadesDestazadas();
        }
        if(establecerInstruccionesHilos.getHiloLlama()==2){
            JOptionPane.showMessageDialog(null,"Lograste destazar a tiempo, conseguiste "+animales[5].getLibrasCarneGenerada()+" lb de carne de Llama");
            establecerInstruccionesHilos.setHiloLlama(1);
            almacenamientoUsuarioAlimentos.setUsuarioLlama(almacenamientoUsuarioAlimentos.getUsuarioLlama()+animales[5].getLibrasCarneGenerada());
            Jugador.jugador1.setEntradaVentas(Jugador.jugador1.getEntradaVentas()+animales[5].getLibrasCarneGenerada());
            EstablecerReportes.sumarUnidadesDestazadas();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccionesjLabel3;
    private javax.swing.JButton AlimentarjButton3;
    public static javax.swing.JButton BodegajButton2;
    private javax.swing.JLabel BodegajLabel2;
    public static javax.swing.JToggleButton ColocarAnimalesjToggleButton1;
    public static javax.swing.JButton ComerjButton2;
    private javax.swing.JLabel ComerjLabel3;
    private javax.swing.JButton ComprarTerrenojButton2;
    private javax.swing.JLabel ComprarTerrenojLabel5;
    private javax.swing.JButton CosecharjButton2;
    private javax.swing.JLabel CosecharjLabel3;
    private javax.swing.JLabel CrearParcelajLabel4;
    private javax.swing.JLabel DarComerAnimalesjLabel2;
    public static javax.swing.JPanel GranjajPanel1;
    public static javax.swing.JToggleButton LimpiarTerrenoCasillajToggleButton3;
    private javax.swing.JLabel LimpiarUnaParcelajLabel2;
    private javax.swing.JLabel LimpiezajLabel2;
    private javax.swing.JLabel LlamadoNickjLabel1;
    private javax.swing.JLabel LogojLabel7;
    private javax.swing.JLabel MenujLabel4;
    public static javax.swing.JButton MercadojButton3;
    private javax.swing.JLabel NoDestacejLabel2;
    public static javax.swing.JLabel OrojLabel2;
    private javax.swing.JLabel OrojLabel6;
    public static javax.swing.JToggleButton ParcelaSinDestacejToggleButton1;
    public static javax.swing.JToggleButton ParcelasjToggleButton5;
    private javax.swing.JLabel PescarjLabel3;
    public static javax.swing.JToggleButton PescarjToggleButton4;
    private javax.swing.JLabel PonerAnimaljLabel7;
    private javax.swing.JLabel ProcesarjLabel1;
    public static javax.swing.JButton ReportesjButton4;
    private javax.swing.JLabel ReportesjLabel1;
    private javax.swing.JButton SeleccionarAnimalesjButton2;
    private javax.swing.JLabel SeleccionarAnimaljLabel8;
    private javax.swing.JButton SeleccionarPlantajButton2;
    private javax.swing.JLabel SeleccionarPlantajLabel7;
    private javax.swing.JLabel SembrarjLabel2;
    public static javax.swing.JToggleButton SiembrarjToggleButton3;
    public static javax.swing.JLabel VidajLabel3;
    private javax.swing.JLabel VidajLabel8;
    public static javax.swing.JProgressBar VidajProgressBar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
