package proyecto1;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jugador.Jugador;
import manejadorDatos.EstablecerReportes;
/**
 *
 * @author Mariano
 */
public class InicioProyecto1 extends javax.swing.JFrame {

    /**
     * Creates new form FrameProyecto1
     */
    FondoInicio fondoInicio = new FondoInicio();
    public InicioProyecto1() {
        this.setContentPane(fondoInicio);
        initComponents();
        EstablecerReportes.creadorDatosReportes();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MensajeIniciojLabel3 = new javax.swing.JLabel();
        MensajeIniciojLabel4 = new javax.swing.JLabel();
        PeticionNombrejLabel1 = new javax.swing.JLabel();
        ReceptorNombrejTextField1 = new javax.swing.JTextField();
        PeticionNickjLabel2 = new javax.swing.JLabel();
        ReceptorNickjTextField2 = new javax.swing.JTextField();
        IniciarJuegojButton1 = new javax.swing.JButton();
        LogojLabel1 = new javax.swing.JLabel();
        SalirDelJuegojButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio del Juego");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel2.setOpaque(false);

        MensajeIniciojLabel3.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        MensajeIniciojLabel3.setForeground(new java.awt.Color(0, 0, 0));
        MensajeIniciojLabel3.setText("MyFarm");

        MensajeIniciojLabel4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        MensajeIniciojLabel4.setForeground(new java.awt.Color(0, 0, 0));
        MensajeIniciojLabel4.setText("BIENVENIDO AL MEJOR EMULADOR DE GRANJA EN TIEMPO REAL");

        PeticionNombrejLabel1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        PeticionNombrejLabel1.setForeground(new java.awt.Color(0, 0, 0));
        PeticionNombrejLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/IngresarNombre.png"))); // NOI18N

        ReceptorNombrejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceptorNombrejTextField1ActionPerformed(evt);
            }
        });

        PeticionNickjLabel2.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        PeticionNickjLabel2.setForeground(new java.awt.Color(0, 0, 0));
        PeticionNickjLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/IngresarNick.png"))); // NOI18N

        ReceptorNickjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceptorNickjTextField2ActionPerformed(evt);
            }
        });

        IniciarJuegojButton1.setBackground(new java.awt.Color(51, 255, 255));
        IniciarJuegojButton1.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        IniciarJuegojButton1.setForeground(new java.awt.Color(0, 0, 0));
        IniciarJuegojButton1.setText("Jugar");
        IniciarJuegojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarJuegojButton1ActionPerformed(evt);
            }
        });

        LogojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Logo.PNG"))); // NOI18N

        SalirDelJuegojButton2.setBackground(new java.awt.Color(255, 0, 0));
        SalirDelJuegojButton2.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        SalirDelJuegojButton2.setForeground(new java.awt.Color(0, 0, 0));
        SalirDelJuegojButton2.setText("Salir");
        SalirDelJuegojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirDelJuegojButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(MensajeIniciojLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PeticionNombrejLabel1)
                    .addComponent(PeticionNickjLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReceptorNombrejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReceptorNickjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LogojLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SalirDelJuegojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(IniciarJuegojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(241, 241, 241))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(MensajeIniciojLabel4)
                                .addGap(28, 28, 28))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(MensajeIniciojLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MensajeIniciojLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PeticionNombrejLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReceptorNombrejTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PeticionNickjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReceptorNickjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(IniciarJuegojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(SalirDelJuegojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogojLabel1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirDelJuegojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirDelJuegojButton2ActionPerformed
        JOptionPane.showMessageDialog(InicioProyecto1.this, "Fin del juego, vuelve pronto");
        System.exit(0);
    }//GEN-LAST:event_SalirDelJuegojButton2ActionPerformed

    private void IniciarJuegojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarJuegojButton1ActionPerformed
        Jugador.jugador1.setNombre(ReceptorNombrejTextField1.getText());
        Jugador.jugador1.setNick(ReceptorNickjTextField2.getText());
        this.setVisible(false);        
        CrearAnimalesPlantas.LlamadoCrearAnimales();
        EstablecerReportes.creadorDatosReportes();
    }//GEN-LAST:event_IniciarJuegojButton1ActionPerformed

    private void ReceptorNickjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceptorNickjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceptorNickjTextField2ActionPerformed

    private void ReceptorNombrejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceptorNombrejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceptorNombrejTextField1ActionPerformed
    class FondoInicio extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/decoracion/ImagenInicio.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    public static void tiempo(){
        
    }

    public static void main(String[] args) {
        
        Jugador.creadorJugador();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() { 
                new InicioProyecto1().setVisible(true);
                
            }
        });
        
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarJuegojButton1;
    private javax.swing.JLabel LogojLabel1;
    private javax.swing.JLabel MensajeIniciojLabel3;
    private javax.swing.JLabel MensajeIniciojLabel4;
    private javax.swing.JLabel PeticionNickjLabel2;
    private javax.swing.JLabel PeticionNombrejLabel1;
    private javax.swing.JTextField ReceptorNickjTextField2;
    private javax.swing.JTextField ReceptorNombrejTextField1;
    private javax.swing.JButton SalirDelJuegojButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
